// <auto-generated />
namespace CourseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class user_rating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_rating));
        
        string IMigrationMetadata.Id
        {
            get { return "201408241454327_user_rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
